import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    include: ["tests/**/*.spec.ts"],
    env: {
      DATABASE_URL: "postgresql://test:test@localhost:5432/test",
      JWT_SECRET: "test_jwt_secret_minimum_32_characters_long",
      INTERNAL_API_KEY: "test-internal-api-key-32-chars-min!!",
      NODE_ENV: "dev",
      RAZORPAY_WEBHOOK_SECRET: "test_webhook_secret_for_security_audit",
      ENABLE_RATE_LIMIT: "false",
    },
    coverage: {
      provider: "v8",
      reporter: ["text", "text-summary", "lcov"],
      include: [
        "src/utilities/authUtils.ts",
        "src/utilities/bookingAccessControl.ts",
        "src/utilities/commonUtils.ts",
        "src/utilities/geoUtils.ts",
        "src/utilities/logSanitizer.ts",
        "src/utilities/originUtils.ts",
        "src/utilities/passwordUtils.ts",
        "src/utilities/payrollUtils.ts",
        "src/utilities/phoneUtils.ts",
        "src/utilities/timezoneUtils.ts",
        "src/errors/**",
        "src/validations/**",
        "src/middlewares/**",
        "src/services/**",
        "src/stores/**",
        "src/realtime/bookingEvents.ts",
        "src/realtime/domainEvents.ts",
        "src/queues/**",
        "src/workers/**",
        "src/api/v1/bookings/stateMachine.ts",
        "src/api/v1/bookings/pricing.ts",
        "src/api/v1/bookings/dispatchStatus.ts",
        "src/api/v1/bookings/assignmentEngine.ts",
        "src/api/v1/bookings/partnerMatcher.ts",
        "src/api/v1/coupons/service.ts",
        "src/api/v1/incentive/service.ts",
        "src/api/v1/uploads/service.ts",
        "src/api/v1/eta/service.ts",
        "src/api/v1/disputes/service.ts",
        "src/api/v1/reviews/service.ts",
        "src/api/v1/partnerZones/service.ts",
        "src/api/v1/services/largeOfficePricing.ts",
        "src/configs/corsConfig.ts",
        "src/configs/dispatchConfig.ts",
        "src/configs/pricingConfig.ts",
      ],
      exclude: [
        "src/middlewares/middlewarehelper/**",
        "src/queues/dispatchTrigger.ts",
        "src/workers/index.ts",
      ],
      thresholds: {
        branches: 90,
        functions: 90,
        lines: 90,
        statements: 90,
      },
    },
  },
});
