export default class ErrorCode {
  static BAD_REQUEST_ERROR = "BAD_REQUEST_ERROR";
  static ENVIRONMENT_CONFIG_ERROR = "ENVIRONMENT_CONFIG_ERROR";
  static EXPIRED_RESOURCE = "EXPIRED_RESOURCE";
  static FORBIDDEN_ERROR = "FORBIDDEN_ERROR";
  static INVALID_JSON_ERROR = "INVALID_JSON_ERROR";
  static INVALID_RESOURCE = "INVALID_RESOURCE";
  static NOT_FOUND_ERROR = "NOT_FOUND_ERROR";
  static RATE_LIMIT_ERROR = "RATE_LIMIT_ERROR";
  static REQUEST_VALIDATION_ERROR = "REQUEST_VALIDATION_ERROR";
  static SERVER_ERROR = "SERVER_ERROR";
  static UNAUTHORIZED_ERROR = "UNAUTHORIZED_ERROR";
  static UNUSED_RESOURCE = "UNUSED_RESOURCE";
  static CONFLICT_ERROR = "CONFLICT_ERROR";
  static EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR";
}
