export { createApiClient } from './client';
export type { ApiConfig } from './client';
export type { ApiResponse, ApiError } from './types';
export { isApiError } from './types';

// Endpoint modules
export {
  createConsumerAuthEndpoints,
  createPartnerAuthEndpoints,
  createAddressesEndpoints,
  createServicesEndpoints,
  createBookingsEndpoints,
  createPaymentsEndpoints,
  createCouponsEndpoints,
  createLocationEndpoints,
  createNotificationsEndpoints,
  createReviewsEndpoints,
  createQuotationsEndpoints,
  createPartnersEndpoints,
  createContactEndpoints,
  createEtaEndpoints,
  createConsumersEndpoints,
  createDisputesEndpoints,
  createReferralsEndpoints,
} from './endpoints';
export type {
  ConsumerValidateResponse,
  PartnerValidateResponse,
  CreateAddressPayload,
  UpdateAddressPayload,
  EstimatePayload,
  EstimateResponse,
  CreateBookingPayload,
  BookingPreview,
  ListBookingsParams,
  ListBookingsResponse,
  TransitionPayload,
  ReschedulePayload,
  AvailabilityPeriodName,
  AvailabilityHourlySlot,
  AvailabilityPeriodGroup,
  AvailabilityAlternativeDay,
  CheckAvailabilityPayload,
  AvailabilityMatchSuccess,
  AvailabilityMatchFailure,
  CheckAvailabilityResponse,
  PaymentConfirmResponse,
  ValidateCouponPayload,
  ValidateCouponResponse,
  CouponOffer,
  CouponDiscountType,
  ListCouponOffersParams,
  ListCouponOffersResponse,
  GeocodedAddress,
  ReverseGeocodeResponse,
  PlacePrediction,
  PlacesSearchResponse,
  PlacesDetailsResponse,
  ServiceabilityResponse,
  RegisterTokenPayload,
  PushPlatform,
  RemoveTokenPayload,
  ListNotificationsParams,
  CreateReviewPayload,
  ListReviewsResponse,
  ListReviewsParams,
  CreateQuotationPayload,
  AddAvailabilityPayload,
  UpdateLocationPayload,
  ContactResponse,
  EtaResponse,
  UpdateConsumerProfilePayload,
} from './endpoints';
